language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t sc4lp3r/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sc4lp3r/docker-react npm run test -- --coverage
